# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NnYsIHNOhHxNn4cCkqWjLNoZeqywZ-wT
"""

speech_hate_words = ["inyenzi", "cockroaches", "kill", "exterminate", "destroy",
    "traitors", "snakes", "rats", "hutu power", "tutsi",
    "ethnic cleansing", "wipe out", "enemy", "revenge",
    "impurity", "traitors", "infiltrators", "parasites "]

# Function to detect hate speech
def detect_hate_speech(text):
    detected_words = [word for word in offensive_words if word in text.lower()]
    return detected_words

# Example usage
speech = "The Tutsis are like cockroaches, they must be exterminated, they must be killed, and we, the Hutus, will be the ones to do it ."
hate_words = detect_hate_speech(text)
if hate_words:
    print("Hate speech detected! Offensive words:", hate_words)
else:
    print("No hate speech detected.")